### ISSUE TITLE
ASAN linking error on Pi

### ISSUE THREAD

**Issue by oppiz** [klavinslab/elma#4]
When porting elme to the Pi  Raspbian Debian 9 (Stretch), you may get the below when you attempt to run the executable after compiling. 

"ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD"

Two options:

LD_PRELOAD=/usr/lib/gcc/arm-linux-gnueabihf/6/libasan.so ./path/to/Executable

change -lasan to -static-libasan in the makefiles.

Other then that elma ports over without modification.

**Comment by klavins** [comment]
Good to know. I will add some smarts to the Makefiles to detect the OS and post a fix for this soon.

**Comment by klavins** [comment]
I have added a conditional definition of `-lasan` or `-static-libasan` to the test and example Makefiles, a flag to hide GCC 7.1 warnings on the pi, and instructions for setting up a pi with all the prerequisites.

For details, see commits ccba67d6895ae2187a23ecb5ae646a24ac9c5d31 and f547832318a0a1f7f3057c51907e3ea247469103.

**Comment by oppiz** [comment]
Worked as expected on a fresh clone of elma on a Pi. Unless you have an issue, im going to count the elma port as part of my project. 

Warnings were suppressed.  
Was able to execute without issue.
